import { StyleSheet } from 'react-native';

export default (styles = StyleSheet.create({
  wrapper: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F9FAFE',
  },
  textInput: {
    width: 80 + '%',
    padding: 12,
    borderRadius: 16,
    elevation: 4,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: 'bold',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF',
    margin: 25,
  },
  bigText: {
    fontSize: 32,
    fontWeight: 'bold',
    padding: 32,
  },
  text: {
    fontSize: 30,
    fontWeight: 'bold',
    margin: 12.5,
  },

  textInputSingUp: {
    width: 80 + '%',
    padding: 10,
    borderRadius: 16,
    elevation: 4,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: 'bold',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF',
    margin: 25,
  },
  mediumText: {
    paddingHorizontal: 16,
    paddingVertical: 4,
    width: '100%',
    textAlign: 'left',
    fontSize: 24,
    fontWeight: 'bold',
    color: 'rgba(0,0,0,0.75)',
  },
  footer: {
    flexDirection: 'row',
    width: '100%',
    height: 64,
    marginBottom: 16,
    backgroundColor: '#F9FAFE',
    justifyContent: 'center',
    alignItems: 'stretch',
    alignSelf: 'flex-end',
  },
  footerTextInput: {
    flex: 8,
    margin: 8,
    borderRadius: 16,
    elevation: 4,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: 'bold',
    backgroundColor: '#FFF',
  },
  footerImages: {
    height: 64,
    width: 64,
    flex: 1,
  },
  searchbar: {
    backgroundColor: '#151146',
    flexDirection: 'row',
    width: '100%',
    paddingTop: 32,
    paddingHorizontal: 16,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-end',
  },
  searchbarTextInput: {
    height: 40,
    flex: 8,
    margin: 8,
    borderRadius: 16,
    elevation: 4,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: 'bold',
    backgroundColor: '#FFF',
  },
  addButton: {
    padding: 16,
    width: 64,
    height: 64,
    position: 'absolute',
    bottom: 24,
    right: 24,
    backgroundColor: '#fff',
    borderRadius: 80,
    borderWidth: 0.25,
    borderColor: 'rgba(0,0,0,0.12)',
    elevation: 8,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
}));
